import = ["~/.config/alacritty/colors.toml"]

[shell]
program = "/bin/bash"
args = ["-l"]

[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "Beam", blinking = "On" } # Beam cursor with blinking enabled
vi_mode_style = { shape = "Block", blinking = "Always" } # Block cursor with always blinking in vi mode
blink_interval = 500    # Set the blinking interval to 500ms (faster blinking)
blink_timeout = 0       # Cursor will never stop blinking
unfocused_hollow = true # Hollow box cursor when unfocused
thickness = 0.2         # Slightly thicker cursor


[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

size = 16.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true



[window]
dimensions = { columns = 150, lines = 50 }
position = { x = 100, y = 100 }
padding = { x = 20, y = 20 }
decorations = "Buttonless"
opacity = 0.85
blur = true
option_as_alt = "Both"
decorations_theme_variant = "Dark"


[selection]
semantic_escape_chars = ".,:;!#$%^&*()[]{}\"'`"

[scrolling]
history = 10000
multiplier = 3

