[colors.primary]
background = "#181818"  
foreground = "#ABABAB"  

[colors.normal]
black   = '#2D2D2D'     
red     = '#D16969'     
green   = '#6A9955'     
yellow  = '#DCDCaa'     
blue    = '#569CD6'     
magenta = '#C586C0'     
cyan    = '#4EC9B0'     
white   = '#D4D4D4'     

[colors.bright]
black   = '#3E4452'     
red     = '#D16969'     
green   = '#B5CEA8'     
yellow  = '#FFD602'     
blue    = '#9CDCFE'     
magenta = '#D7BA7D'     
cyan    = '#00FFFF'    
white   = '#FFFFFF'    

