[colors.primary]
background = "#1F1F1F"
foreground = "#CCCCCC"

[colors.normal]
black   = '#373737' # A lighter gray to replace the dark black
red     = '#F44747' # vscRed
green   = '#6A9955' # vscGreen
yellow  = '#DCDCAA' # vscYellow
blue    = '#569CD6' # vscBlue
magenta = '#C586C0' # vscPink
cyan    = '#4EC9B0' # vscBlueGreen
white   = '#D4D4D4' # vscFront

[colors.bright]
black   = '#5A5A5A' # vscLineNumber
red     = '#D16969' # vscLightRed
green   = '#B5CEA8' # vscLightGreen
yellow  = '#FFD602' # vscDarkYellow
blue    = '#9CDCFE' # vscLightBlue
magenta = '#CE9178' # vscOrange
cyan    = '#00FFFF' # Keep the existing cyan
white   = '#FFFFFF' # Keep the existing bright white

