-- https://github.com/golang/tools/blob/master/gopls/doc/settings.md
return {
	settings = {
		gopls = {
			hints = {
				rangeVariableTypes = true,
				parameterNames = true,
				constantValues = true,
				assignVariableTypes = true,
				compositeLiteralFields = true,
				compositeLiteralTypes = true,
				functionTypeParameters = true,
			},
			usePlaceholders = true,
			completeUnimported = true,
			staticcheck = true,
			semanticTokens = true,
			directoryFilters = { "-.git", "-node_modules" },
			analyses = {
				nilness = true,
				unusedparams = true,
				unusedwrite = true,
				useany = true,
				shadow = true,
				unusedvariable = true,
				defers = true,
				httpresponse = true,
				stringintconv = true,
				lostcancel = true,
				printf = true,
				structtag = true,
				testinggoroutine = true,
				deepequalerrors = true,
				timeformat = true,
				unusedresult = true,
				atomicalign = true,
				sigchanyzer = true,
				slog = true,
			},
			vulncheck = "Imports",
			gofumpt = true,
			linksInHover = "gopls",
			symbolStyle = "Dynamic",
			importShortcut = "Both",
			diagnosticsDelay = "500ms",
			codelenses = {
				generate = true,
				regenerate_cgo = true,
				run_govulncheck = true,
				tidy = true,
				upgrade_dependency = true,
				vendor = true,
			},
		},
	},
}
