background {
    monitor =
    path = screenshot
    blur_passes = 2
}

input-field {
    monitor =
    size = 600, 100
    outline_thickness = 10 

    position = 0, 0
    halign = center
    valign = center
}
